version: '3.4'
services:
  weaviate:
    image: semitechnologies/weaviate:1.20.3
    restart: on-failure:0
    ports:
     - "8080:8080"
    env_file:
      - weaviate.env
    
  app:
    build: ../services
    env_file:
      - app.env
    ports:
     - "8081:8081"
    depends_on:
      - weaviate
    restart: always

